In [28]:
import numpy as np
import itertools

def is_valid_matrix(matrix):
    # Check if each row sums to 0
    # 检查是否每行之和均为0
    if not all(np.sum(matrix, axis=0) == 0):
        return False
    else:
        return True

def generate_matrix(times, number_of_balls):
    elements = [-1, 0, 1]
    # Generate all possible combinations of 3 elements from [-1, 0, 1]
    # 生成所有[-1, 0, 1]组成的三维向量组合
    possible_rows = [row for row in np.array(np.meshgrid(*[elements] * times)).T.reshape(-1,times)]
    # Pair vectors whose sum is 0
    # 把和为0的向量两两组成一对
    pairs = []
    for i in range(len(possible_rows)//2):
        pairs.append([possible_rows[i], possible_rows[-i-1]])

    # For each combination, enumerate every choice
    # 对于每种组合，枚举每对中的选择
    combinations = itertools.combinations(pairs, number_of_balls)
    for combination in combinations:
        # For each pair, choose one of it
        # 对 12 对中的每对，选择其中一个 np.array
        choices = itertools.product(*combination) 
        for choice in choices:
            # Form a matrix using the 12 choosed vectors
            # 将选中的 12 个 np.array 组成一个矩阵
            matrix = np.stack(choice) 

            if is_valid_matrix(matrix):
                return matrix.T
    return "No result"

# Generate the matrix
# 生成矩阵
matrix = generate_matrix(3,12)
print(matrix)


[[-1 -1 -1  0  0  0  1 -1  1  1  1  0]
 [-1  0  1  1  0 -1 -1  0  1  0 -1  1]
 [-1 -1 -1  1  1  1 -1  1  0  0  0  0]]
